# TCL File Generated by Component Editor 13.0sp1
# Tue Apr 07 10:44:21 ICT 2026
# DO NOT MODIFY


# 
# DES "DES" v1.0
#  2026.04.07.10:44:21
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module DES
# 
set_module_property DESCRIPTION ""
set_module_property NAME DES
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DES
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DES_AVALON_WRAPPER
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file DES_ALGORITHM.v VERILOG PATH DES_ALGORITHM.v
add_fileset_file DES_CONTROL.v VERILOG PATH DES_CONTROL.v
add_fileset_file E_MATRIX.v VERILOG PATH E_MATRIX.v
add_fileset_file E_XOR_KEY.v VERILOG PATH E_XOR_KEY.v
add_fileset_file F_FUNCTION.v VERILOG PATH F_FUNCTION.v
add_fileset_file IP.v VERILOG PATH IP.v
add_fileset_file IP_1.v VERILOG PATH IP_1.v
add_fileset_file MUX2_1_TOP.v VERILOG PATH MUX2_1_TOP.v
add_fileset_file P_MATRIX.v VERILOG PATH P_MATRIX.v
add_fileset_file PC_1.v VERILOG PATH PC_1.v
add_fileset_file PC_2.v VERILOG PATH PC_2.v
add_fileset_file S_BOX.v VERILOG PATH S_BOX.v
add_fileset_file SHIFT_LEFT_1.v VERILOG PATH SHIFT_LEFT_1.v
add_fileset_file SHIFT_LEFT_2.v VERILOG PATH SHIFT_LEFT_2.v
add_fileset_file DES_AVALON_WRAPPER.v VERILOG PATH DES_AVALON_WRAPPER.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

